/*
 * This file is generated by jOOQ.
 */
package vn.hieplp.todo.repositories.generates;


import vn.hieplp.todo.repositories.generates.tables.*;


/**
 * Convenience access to all tables in todo.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>todo.note</code>.
     */
    public static final Note NOTE = Note.NOTE;

    /**
     * The table <code>todo.password</code>.
     */
    public static final Password PASSWORD = Password.PASSWORD;

    /**
     * The table <code>todo.task</code>.
     */
    public static final Task TASK = Task.TASK;

    /**
     * The table <code>todo.template</code>.
     */
    public static final Template TEMPLATE = Template.TEMPLATE;

    /**
     * The table <code>todo.user</code>.
     */
    public static final User USER = User.USER;
}
