/*
 * This file is generated by jOOQ.
 */
package vn.hieplp.todo.repositories.generates;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import vn.hieplp.todo.repositories.generates.tables.*;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Todo extends SchemaImpl {

    /**
     * The reference instance of <code>todo</code>
     */
    public static final Todo TODO = new Todo();
    private static final long serialVersionUID = 1L;
    /**
     * The table <code>todo.note</code>.
     */
    public final Note NOTE = Note.NOTE;

    /**
     * The table <code>todo.password</code>.
     */
    public final Password PASSWORD = Password.PASSWORD;

    /**
     * The table <code>todo.task</code>.
     */
    public final Task TASK = Task.TASK;

    /**
     * The table <code>todo.template</code>.
     */
    public final Template TEMPLATE = Template.TEMPLATE;

    /**
     * The table <code>todo.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Todo() {
        super("todo", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
                Note.NOTE,
                Password.PASSWORD,
                Task.TASK,
                Template.TEMPLATE,
                User.USER);
    }
}
