export const CodeResponse = {
    FORBIDDEN: "403",
    NOT_FOUND: "404",
    GAME_IS_GOING_ON: "GAME_4000",
    JOIN_OWN_GAME: "GAME_4001",
    GAME_IS_NOT_GOING_ON: "GAME_4002",
    NOT_USER_TURN: "GAME_4003",
}

export const Status = {
    NOT_FOUND: 5,
    ALREADY_EXISTS: 6,
    PERMISSION_DENIED: 7,
    UNAVAILABLE: 14,
    UNAUTHENTICATED: 16
}