/*
 * This file is generated by jOOQ.
 */
package vn.hieplp.todo.repositories.generates.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import vn.hieplp.todo.repositories.generates.tables.Note;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class NoteRecord extends UpdatableRecordImpl<NoteRecord> implements Record10<String, String, String, Integer, String, String, LocalDateTime, String, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached NoteRecord
     */
    public NoteRecord() {
        super(Note.NOTE);
    }

    /**
     * Create a detached, initialised NoteRecord
     */
    public NoteRecord(String noteid, String notetitle, String notedescription, Integer notestatus, String userid, String createdby, LocalDateTime createdat, String modifiedby, LocalDateTime modifiedat, Integer ispinned) {
        super(Note.NOTE);

        setNoteid(noteid);
        setNotetitle(notetitle);
        setNotedescription(notedescription);
        setNotestatus(notestatus);
        setUserid(userid);
        setCreatedby(createdby);
        setCreatedat(createdat);
        setModifiedby(modifiedby);
        setModifiedat(modifiedat);
        setIspinned(ispinned);
    }

    /**
     * Getter for <code>todo.note.noteId</code>.
     */
    public String getNoteid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>todo.note.noteId</code>.
     */
    public void setNoteid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>todo.note.noteTitle</code>.
     */
    public String getNotetitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>todo.note.noteTitle</code>.
     */
    public void setNotetitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>todo.note.noteDescription</code>.
     */
    public String getNotedescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>todo.note.noteDescription</code>.
     */
    public void setNotedescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>todo.note.noteStatus</code>.
     */
    public Integer getNotestatus() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>todo.note.noteStatus</code>.
     */
    public void setNotestatus(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>todo.note.userId</code>.
     */
    public String getUserid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>todo.note.userId</code>.
     */
    public void setUserid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>todo.note.createdBy</code>.
     */
    public String getCreatedby() {
        return (String) get(5);
    }

    /**
     * Setter for <code>todo.note.createdBy</code>.
     */
    public void setCreatedby(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>todo.note.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>todo.note.createdAt</code>.
     */
    public void setCreatedat(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>todo.note.modifiedBy</code>.
     */
    public String getModifiedby() {
        return (String) get(7);
    }

    /**
     * Setter for <code>todo.note.modifiedBy</code>.
     */
    public void setModifiedby(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>todo.note.modifiedAt</code>.
     */
    public LocalDateTime getModifiedat() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>todo.note.modifiedAt</code>.
     */
    public void setModifiedat(LocalDateTime value) {
        set(8, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>todo.note.isPinned</code>.
     */
    public Integer getIspinned() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>todo.note.isPinned</code>.
     */
    public void setIspinned(Integer value) {
        set(9, value);
    }

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    @Override
    public Row10<String, String, String, Integer, String, String, LocalDateTime, String, LocalDateTime, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<String, String, String, Integer, String, String, LocalDateTime, String, LocalDateTime, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Note.NOTE.NOTEID;
    }

    @Override
    public Field<String> field2() {
        return Note.NOTE.NOTETITLE;
    }

    @Override
    public Field<String> field3() {
        return Note.NOTE.NOTEDESCRIPTION;
    }

    @Override
    public Field<Integer> field4() {
        return Note.NOTE.NOTESTATUS;
    }

    @Override
    public Field<String> field5() {
        return Note.NOTE.USERID;
    }

    @Override
    public Field<String> field6() {
        return Note.NOTE.CREATEDBY;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Note.NOTE.CREATEDAT;
    }

    @Override
    public Field<String> field8() {
        return Note.NOTE.MODIFIEDBY;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Note.NOTE.MODIFIEDAT;
    }

    @Override
    public Field<Integer> field10() {
        return Note.NOTE.ISPINNED;
    }

    @Override
    public String component1() {
        return getNoteid();
    }

    @Override
    public String component2() {
        return getNotetitle();
    }

    @Override
    public String component3() {
        return getNotedescription();
    }

    @Override
    public Integer component4() {
        return getNotestatus();
    }

    @Override
    public String component5() {
        return getUserid();
    }

    @Override
    public String component6() {
        return getCreatedby();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedat();
    }

    @Override
    public String component8() {
        return getModifiedby();
    }

    @Override
    public LocalDateTime component9() {
        return getModifiedat();
    }

    @Override
    public Integer component10() {
        return getIspinned();
    }

    @Override
    public String value1() {
        return getNoteid();
    }

    @Override
    public String value2() {
        return getNotetitle();
    }

    @Override
    public String value3() {
        return getNotedescription();
    }

    @Override
    public Integer value4() {
        return getNotestatus();
    }

    @Override
    public String value5() {
        return getUserid();
    }

    @Override
    public String value6() {
        return getCreatedby();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedat();
    }

    @Override
    public String value8() {
        return getModifiedby();
    }

    @Override
    public LocalDateTime value9() {
        return getModifiedat();
    }

    @Override
    public Integer value10() {
        return getIspinned();
    }

    @Override
    public NoteRecord value1(String value) {
        setNoteid(value);
        return this;
    }

    @Override
    public NoteRecord value2(String value) {
        setNotetitle(value);
        return this;
    }

    @Override
    public NoteRecord value3(String value) {
        setNotedescription(value);
        return this;
    }

    @Override
    public NoteRecord value4(Integer value) {
        setNotestatus(value);
        return this;
    }

    @Override
    public NoteRecord value5(String value) {
        setUserid(value);
        return this;
    }

    @Override
    public NoteRecord value6(String value) {
        setCreatedby(value);
        return this;
    }

    @Override
    public NoteRecord value7(LocalDateTime value) {
        setCreatedat(value);
        return this;
    }

    @Override
    public NoteRecord value8(String value) {
        setModifiedby(value);
        return this;
    }

    @Override
    public NoteRecord value9(LocalDateTime value) {
        setModifiedat(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public NoteRecord value10(Integer value) {
        setIspinned(value);
        return this;
    }

    @Override
    public NoteRecord values(String value1, String value2, String value3, Integer value4, String value5, String value6, LocalDateTime value7, String value8, LocalDateTime value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }
}
