/*
 * This file is generated by jOOQ.
 */
package vn.hieplp.todo.repositories.generates.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Password implements Serializable {

    private static final long serialVersionUID = 1L;

    private String userid;
    private byte[] password;
    private byte[] salt;

    public Password() {
    }

    public Password(Password value) {
        this.userid = value.userid;
        this.password = value.password;
        this.salt = value.salt;
    }

    public Password(
            String userid,
            byte[] password,
            byte[] salt
    ) {
        this.userid = userid;
        this.password = password;
        this.salt = salt;
    }

    /**
     * Getter for <code>todo.password.userId</code>.
     */
    public String getUserid() {
        return this.userid;
    }

    /**
     * Setter for <code>todo.password.userId</code>.
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * Getter for <code>todo.password.password</code>.
     */
    public byte[] getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>todo.password.password</code>.
     */
    public void setPassword(byte[] password) {
        this.password = password;
    }

    /**
     * Getter for <code>todo.password.salt</code>.
     */
    public byte[] getSalt() {
        return this.salt;
    }

    /**
     * Setter for <code>todo.password.salt</code>.
     */
    public void setSalt(byte[] salt) {
        this.salt = salt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Password (");

        sb.append(userid);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
