/*
 * This file is generated by jOOQ.
 */
package vn.hieplp.todo.repositories.generates.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Task implements Serializable {

    private static final long serialVersionUID = 1L;

    private String taskid;
    private String userid;
    private String tasktitle;
    private String taskdescription;
    private LocalDateTime taskdate;
    private String taskimages;
    private Integer taskstatus;
    private String createdby;
    private LocalDateTime createdat;
    private String modifiedby;
    private LocalDateTime modifiedat;

    public Task() {
    }

    public Task(Task value) {
        this.taskid = value.taskid;
        this.userid = value.userid;
        this.tasktitle = value.tasktitle;
        this.taskdescription = value.taskdescription;
        this.taskdate = value.taskdate;
        this.taskimages = value.taskimages;
        this.taskstatus = value.taskstatus;
        this.createdby = value.createdby;
        this.createdat = value.createdat;
        this.modifiedby = value.modifiedby;
        this.modifiedat = value.modifiedat;
    }

    public Task(
            String taskid,
            String userid,
            String tasktitle,
            String taskdescription,
            LocalDateTime taskdate,
            String taskimages,
            Integer taskstatus,
            String createdby,
            LocalDateTime createdat,
            String modifiedby,
            LocalDateTime modifiedat
    ) {
        this.taskid = taskid;
        this.userid = userid;
        this.tasktitle = tasktitle;
        this.taskdescription = taskdescription;
        this.taskdate = taskdate;
        this.taskimages = taskimages;
        this.taskstatus = taskstatus;
        this.createdby = createdby;
        this.createdat = createdat;
        this.modifiedby = modifiedby;
        this.modifiedat = modifiedat;
    }

    /**
     * Getter for <code>todo.task.taskId</code>.
     */
    public String getTaskid() {
        return this.taskid;
    }

    /**
     * Setter for <code>todo.task.taskId</code>.
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid;
    }

    /**
     * Getter for <code>todo.task.userId</code>.
     */
    public String getUserid() {
        return this.userid;
    }

    /**
     * Setter for <code>todo.task.userId</code>.
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * Getter for <code>todo.task.taskTitle</code>.
     */
    public String getTasktitle() {
        return this.tasktitle;
    }

    /**
     * Setter for <code>todo.task.taskTitle</code>.
     */
    public void setTasktitle(String tasktitle) {
        this.tasktitle = tasktitle;
    }

    /**
     * Getter for <code>todo.task.taskDescription</code>.
     */
    public String getTaskdescription() {
        return this.taskdescription;
    }

    /**
     * Setter for <code>todo.task.taskDescription</code>.
     */
    public void setTaskdescription(String taskdescription) {
        this.taskdescription = taskdescription;
    }

    /**
     * Getter for <code>todo.task.taskDate</code>.
     */
    public LocalDateTime getTaskdate() {
        return this.taskdate;
    }

    /**
     * Setter for <code>todo.task.taskDate</code>.
     */
    public void setTaskdate(LocalDateTime taskdate) {
        this.taskdate = taskdate;
    }

    /**
     * Getter for <code>todo.task.taskImages</code>.
     */
    public String getTaskimages() {
        return this.taskimages;
    }

    /**
     * Setter for <code>todo.task.taskImages</code>.
     */
    public void setTaskimages(String taskimages) {
        this.taskimages = taskimages;
    }

    /**
     * Getter for <code>todo.task.taskStatus</code>.
     */
    public Integer getTaskstatus() {
        return this.taskstatus;
    }

    /**
     * Setter for <code>todo.task.taskStatus</code>.
     */
    public void setTaskstatus(Integer taskstatus) {
        this.taskstatus = taskstatus;
    }

    /**
     * Getter for <code>todo.task.createdBy</code>.
     */
    public String getCreatedby() {
        return this.createdby;
    }

    /**
     * Setter for <code>todo.task.createdBy</code>.
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    /**
     * Getter for <code>todo.task.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return this.createdat;
    }

    /**
     * Setter for <code>todo.task.createdAt</code>.
     */
    public void setCreatedat(LocalDateTime createdat) {
        this.createdat = createdat;
    }

    /**
     * Getter for <code>todo.task.modifiedBy</code>.
     */
    public String getModifiedby() {
        return this.modifiedby;
    }

    /**
     * Setter for <code>todo.task.modifiedBy</code>.
     */
    public void setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby;
    }

    /**
     * Getter for <code>todo.task.modifiedAt</code>.
     */
    public LocalDateTime getModifiedat() {
        return this.modifiedat;
    }

    /**
     * Setter for <code>todo.task.modifiedAt</code>.
     */
    public void setModifiedat(LocalDateTime modifiedat) {
        this.modifiedat = modifiedat;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Task (");

        sb.append(taskid);
        sb.append(", ").append(userid);
        sb.append(", ").append(tasktitle);
        sb.append(", ").append(taskdescription);
        sb.append(", ").append(taskdate);
        sb.append(", ").append(taskimages);
        sb.append(", ").append(taskstatus);
        sb.append(", ").append(createdby);
        sb.append(", ").append(createdat);
        sb.append(", ").append(modifiedby);
        sb.append(", ").append(modifiedat);

        sb.append(")");
        return sb.toString();
    }
}
