/*
 * This file is generated by jOOQ.
 */
package vn.hieplp.todo.repositories.generates.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    private String userid;
    private String email;
    private String fullname;
    private Integer userstatus;

    public User() {
    }

    public User(User value) {
        this.userid = value.userid;
        this.email = value.email;
        this.fullname = value.fullname;
        this.userstatus = value.userstatus;
    }

    public User(
            String userid,
            String email,
            String fullname,
            Integer userstatus
    ) {
        this.userid = userid;
        this.email = email;
        this.fullname = fullname;
        this.userstatus = userstatus;
    }

    /**
     * Getter for <code>todo.user.userId</code>.
     */
    public String getUserid() {
        return this.userid;
    }

    /**
     * Setter for <code>todo.user.userId</code>.
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * Getter for <code>todo.user.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>todo.user.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>todo.user.fullName</code>.
     */
    public String getFullname() {
        return this.fullname;
    }

    /**
     * Setter for <code>todo.user.fullName</code>.
     */
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    /**
     * Getter for <code>todo.user.userStatus</code>.
     */
    public Integer getUserstatus() {
        return this.userstatus;
    }

    /**
     * Setter for <code>todo.user.userStatus</code>.
     */
    public void setUserstatus(Integer userstatus) {
        this.userstatus = userstatus;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(userid);
        sb.append(", ").append(email);
        sb.append(", ").append(fullname);
        sb.append(", ").append(userstatus);

        sb.append(")");
        return sb.toString();
    }
}
